steps:
  # Step 1: Run tests
  - name: 'maven:3.6.3-openjdk-8'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🧪 Running tests with Java 8..."
        mvn clean test -B -Dstyle.color=always
    id: 'test'

  # Step 2: Build application
  - name: 'maven:3.6.3-openjdk-8'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔨 Building application..."
        mvn clean package -DskipTests -B
    id: 'build'
    waitFor: ['test']

  # Step 3: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/java-user-app:latest'
      - '.'
    id: 'docker-build'
    waitFor: ['build']

  # Step 4: Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/java-user-app:latest'
    id: 'push'
    waitFor: ['docker-build']

  # Step 5: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'java-user-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/java-user-app:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '2'
    id: 'deploy'
    waitFor: ['push']

# 修复日志配置
options:
  logging: CLOUD_LOGGING_ONLY

# Build timeout
timeout: '3600s'

# Images to be pushed
images:
  - 'gcr.io/$PROJECT_ID/java-user-app:latest'